typography_spectrum: 0.05349621269851923
color:
  saturation: 0.7621682998724282
  brandStrength: 0.2913926655892283
  lightness: 0.6292206989601254
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  rhythmicContrast: 0.9405356806237251
layout_spectrum: 0.03604237479157746
analytics:
  google: UA-9523612-5
name: Dave La Cava
navigation:
  - name: Works
    id: f4e1a472-75ed-48dc-9e5f-15f0395c4adc
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Welcome
