layout_spectrum: 0.7768148
typography_spectrum: 0.3943839
color:
  saturation: 0.09415162
  lightness: 0.2681662
  brandStrength: 0.9485127
  rhythmicContrast: 0.713767
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Dave La Cava
